// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	RegisterNick
	JoinRoom
	LeaveRoom
	Disconnect
	ChatMessage
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_REGISTERNICK MessageType = 0
	MessageType_JOINROOM     MessageType = 1
	MessageType_LEAVEROOM    MessageType = 2
	MessageType_DISCONNECT   MessageType = 3
	MessageType_CHATMESSAGE  MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "REGISTERNICK",
	1: "JOINROOM",
	2: "LEAVEROOM",
	3: "DISCONNECT",
	4: "CHATMESSAGE",
}
var MessageType_value = map[string]int32{
	"REGISTERNICK": 0,
	"JOINROOM":     1,
	"LEAVEROOM":    2,
	"DISCONNECT":   3,
	"CHATMESSAGE":  4,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	Type    MessageType `protobuf:"varint,1,opt,name=type,enum=message.MessageType" json:"type,omitempty"`
	Content []byte      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RegisterNick struct {
	Nick string `protobuf:"bytes,1,opt,name=nick" json:"nick,omitempty"`
}

func (m *RegisterNick) Reset()                    { *m = RegisterNick{} }
func (m *RegisterNick) String() string            { return proto.CompactTextString(m) }
func (*RegisterNick) ProtoMessage()               {}
func (*RegisterNick) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type JoinRoom struct {
	Room string `protobuf:"bytes,1,opt,name=room" json:"room,omitempty"`
}

func (m *JoinRoom) Reset()                    { *m = JoinRoom{} }
func (m *JoinRoom) String() string            { return proto.CompactTextString(m) }
func (*JoinRoom) ProtoMessage()               {}
func (*JoinRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LeaveRoom struct {
	Room string `protobuf:"bytes,1,opt,name=room" json:"room,omitempty"`
}

func (m *LeaveRoom) Reset()                    { *m = LeaveRoom{} }
func (m *LeaveRoom) String() string            { return proto.CompactTextString(m) }
func (*LeaveRoom) ProtoMessage()               {}
func (*LeaveRoom) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Disconnect struct {
}

func (m *Disconnect) Reset()                    { *m = Disconnect{} }
func (m *Disconnect) String() string            { return proto.CompactTextString(m) }
func (*Disconnect) ProtoMessage()               {}
func (*Disconnect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ChatMessage struct {
	From string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ChatMessage) Reset()                    { *m = ChatMessage{} }
func (m *ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()               {}
func (*ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*RegisterNick)(nil), "message.RegisterNick")
	proto.RegisterType((*JoinRoom)(nil), "message.JoinRoom")
	proto.RegisterType((*LeaveRoom)(nil), "message.LeaveRoom")
	proto.RegisterType((*Disconnect)(nil), "message.Disconnect")
	proto.RegisterType((*ChatMessage)(nil), "message.ChatMessage")
	proto.RegisterEnum("message.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x2d, 0x25, 0x22, 0x53, 0x5a, 0xc9, 0xc4, 0x03, 0x27, 0x35, 0x7b, 0x6a, 0x3c, 0xf4,
	0xa0, 0xbf, 0x80, 0xd0, 0x4d, 0x45, 0x05, 0x92, 0x85, 0x78, 0xf3, 0x80, 0xb8, 0x56, 0x62, 0xca,
	0x36, 0xb0, 0x31, 0xf1, 0xdf, 0x3b, 0xbb, 0x2d, 0xd1, 0x8b, 0xa7, 0xf9, 0x26, 0xef, 0xcd, 0xce,
	0x9b, 0x85, 0xf9, 0x4e, 0x0e, 0x43, 0xbd, 0x95, 0xab, 0x7d, 0xaf, 0xb4, 0x42, 0xef, 0xd8, 0xb2,
	0x0c, 0xbc, 0xec, 0x80, 0xb8, 0x04, 0x57, 0x7f, 0xef, 0x65, 0x34, 0xb9, 0x9e, 0x2c, 0x17, 0xb7,
	0x17, 0xab, 0x71, 0xe2, 0xa8, 0x57, 0xa4, 0x09, 0xeb, 0xc0, 0x08, 0xbc, 0x46, 0x75, 0x5a, 0x76,
	0x3a, 0x72, 0xc8, 0x1c, 0x88, 0xb1, 0x65, 0x0c, 0x02, 0x21, 0xb7, 0xed, 0xa0, 0x65, 0x9f, 0xb7,
	0xcd, 0x27, 0x22, 0xb8, 0x1d, 0x55, 0xfb, 0xa6, 0x2f, 0x2c, 0xb3, 0x4b, 0x38, 0x7b, 0x50, 0x6d,
	0x27, 0x94, 0xda, 0x19, 0xbd, 0xa7, 0x3a, 0xea, 0x86, 0xd9, 0x15, 0xf8, 0x4f, 0xb2, 0xfe, 0x92,
	0xff, 0x1a, 0x02, 0x80, 0x75, 0x3b, 0xd0, 0xca, 0x4e, 0x36, 0x9a, 0x71, 0x98, 0x25, 0x1f, 0xb5,
	0x1e, 0xaf, 0xa0, 0x81, 0xf7, 0xfe, 0x77, 0xc0, 0x30, 0x2e, 0xc0, 0xd1, 0xca, 0x46, 0xf5, 0x05,
	0x91, 0xf1, 0xbc, 0xd5, 0xba, 0x8e, 0xa6, 0x07, 0x8f, 0xe1, 0x9b, 0x17, 0x98, 0xfd, 0x39, 0x14,
	0x43, 0x3a, 0x84, 0x6f, 0xd2, 0xb2, 0xe2, 0x22, 0x4f, 0x93, 0xc7, 0xf0, 0x04, 0x03, 0x8a, 0x5d,
	0xa4, 0xb9, 0x28, 0x8a, 0x2c, 0x9c, 0xe0, 0x9c, 0x42, 0xf2, 0xf8, 0x99, 0xdb, 0xd6, 0xa1, 0x0d,
	0xb0, 0x4e, 0xcb, 0xa4, 0xc8, 0x73, 0x9e, 0x54, 0xe1, 0x14, 0xcf, 0x29, 0xd4, 0x7d, 0x5c, 0x65,
	0xbc, 0x2c, 0xe3, 0x0d, 0x0f, 0xdd, 0xd7, 0x53, 0xfb, 0xef, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x3b, 0x6b, 0xda, 0xaa, 0x88, 0x01, 0x00, 0x00,
}
